pipeline:
  name: start-training
description: a pipeline that runs a bash script to start training job on ngc.
input:
  pfs:
    glob: /*
    repo: deeplearning-training-images
transform:
  cmd:
    - bash -x ./startjob.sh
  image: nvcr.io/nvidian/sae/joliao-start-training-job:1.9
  image_pull_secrets:
    - nvcr.io
