pipeline:
  name: upload-to-ngc
description: a pipeline that runs a bash script to upload results to ngc.
input:
  pfs:
    glob: /*
    repo: start-validation
transform:
  cmd:
    - ./startvalidation.sh
    - cd /pfs/out && touch done.txt
  image: nvcr.io/nvidian/sae/joliao-upload-to-ngc-job:1.0
  image_pull_secrets:
    - nvcr.io
