pipeline:
  name: upload-dataset
description: a pipeline that runs a bash script to upload data from pachyderm repo to a bcp dataset.
input:
  pfs:
    glob: /*
    repo: deeplearning-training-images
transform:
  cmd: ['/bin/sh']
  stdin: ['bash -x ./upload-dataset.sh']
  image: nvcr.io/nvidian/sae/joliao-upload-to-dataset:1.8
  image_pull_secrets:
    - nvcr.io
